name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  example_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
          architecture: x64
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          ignore: "F401"
          exclude: "./src/main_flake_fail.py"
          max-line-length: "100"
          path: "src"
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=src/main_sonar_fail.py
            -Dsonar.tests=src/main_tests.py
            -Dsonar.verbose=true